"""empty message

Revision ID: 6ae94c0b9c61
Revises: f114427e005d
Create Date: 2023-06-26 14:14:15.832806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae94c0b9c61'
down_revision = 'f114427e005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_pets')
    op.drop_table('pets')
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('species', sa.VARCHAR(), nullable=True),
    sa.Column('breed', sa.VARCHAR(), nullable=True),
    sa.Column('temperament', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
